apiVersion: v1
kind: Service
metadata:
  name: python-monitor-app-service
spec:
  type: LoadBalancer
  selector:
    app: python-monitor-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
